import type { LibraryRecord, Task } from "./domain";

export const skills = [
  { name: "爆款拆解", description: "结构 · 钩子 · 情绪", prompt: "请使用「爆款拆解」技能，处理以下内容：" },
  { name: "爆款选题指导", description: "趋势 · 人群 · 切角", prompt: "请使用「爆款选题指导」技能，分析：" },
  { name: "采集内容", description: "单篇 · 关键词 · 博主", prompt: "请使用「采集内容」技能，采集：" },
  { name: "文案仿写", description: "参考结构重新表达", prompt: "请使用「文案仿写」技能，参考以下内容重新表达：" },
  { name: "一键采集仿写", description: "采集后直接生成初稿", prompt: "请使用「一键采集仿写」技能，处理以下内容：" },
  { name: "文案原创", description: "从选题生成完整文案", prompt: "请使用「文案原创」技能，围绕以下选题创作：" },
];

export const collectionRecords: LibraryRecord[] = [
  {
    id: "S-001",
    title: "从小白到 AI 万粉博主，敢想比敢做更重要",
    status: "已完成",
    type: "图文",
    source: "小红书",
    author: "林小满",
    updatedAt: "今天 11:18",
    updatedAtIso: "2026-08-31T11:18:00+08:00",
    publishedAt: "2026-08-30T09:00:00+08:00",
    summary: "用三次内容迭代讲清从工具收藏到稳定创作工作流的转变。",
    tags: ["AI 工作流", "成长复盘"],
    version: "v1",
    sourceId: "xhs_demo_001",
    contentType: "图文",
    provider: "sandbox-v1",
    benchmark: true,
    categoryTags: ["AI", "教程"],
  },
  {
    id: "S-002",
    title: "用 AI 发掘财富机会，思路值得借鉴",
    status: "已完成",
    type: "视频",
    source: "小红书",
    author: "产品林悦",
    updatedAt: "今天 10:52",
    updatedAtIso: "2026-08-31T10:52:00+08:00",
    publishedAt: "2026-08-29T09:00:00+08:00",
    summary: "从需求识别、验证到小步上线，给出面向普通人的 AI 项目路线。",
    tags: ["AI 副业", "产品思维"],
    version: "v2",
    sourceId: "xhs_demo_002",
    contentType: "视频",
    provider: "tikhub-v1",
    categoryTags: ["AI", "机会"],
  },
  {
    id: "S-003",
    title: "抓住 AI 时代红利，很多人还没意识到",
    status: "部分完成",
    type: "视频",
    source: "小红书",
    author: "阿策说 AI",
    updatedAt: "今天 09:42",
    updatedAtIso: "2026-08-31T09:42:00+08:00",
    publishedAt: "2026-08-28T09:00:00+08:00",
    summary: "正文与互动数据已入库，视频文案转写失败，可单独重试。",
    tags: ["行业观察", "AI 趋势"],
    version: "v1",
    sourceId: "xhs_demo_003",
    risk: "视频文案待重试",
    contentType: "视频",
    provider: "tikhub-v1",
    categoryTags: ["行业"],
  },
  {
    id: "S-004",
    title: "男生精简护肤指南（适配各种肤质）",
    status: "已完成",
    type: "图文",
    source: "小红书",
    author: "成分派 Leo",
    updatedAt: "昨天 18:20",
    updatedAtIso: "2026-08-30T18:20:00+08:00",
    publishedAt: "2026-08-27T09:00:00+08:00",
    summary: "以最少步骤降低行动门槛，评论区问题高度集中。",
    tags: ["低粉爆款", "竞品对标"],
    version: "v1",
    sourceId: "xhs_demo_004",
    contentType: "图文",
    provider: "xiaohongshu-web-v1",
    benchmark: true,
    categoryTags: ["美妆", "对标"],
  },
];

export const breakdownRecords: LibraryRecord[] = [
  {
    ...collectionRecords[0],
    id: "B-001",
    status: "已完成",
    type: "爆款拆解",
    source: "S-001",
    summary: "反常识提问开场 → 个人失败经历 → 三步方法 → 低门槛行动号召。",
    version: "v2",
  },
  {
    ...collectionRecords[1],
    id: "B-002",
    status: "已完成",
    type: "爆款拆解",
    source: "S-002",
    summary: "用机会焦虑吸引注意，再以确定性流程降低不安；事实承诺需要降级。",
    version: "v1",
    risk: "避免收益保证",
  },
  {
    ...collectionRecords[3],
    id: "B-003",
    status: "部分完成",
    type: "爆款拆解",
    source: "S-004",
    summary: "问题清单式结构完整，视觉分析任务失败，文字结论仍可使用。",
    version: "v1",
    risk: "视觉分析待重试",
  },
];

export const creationRecords: LibraryRecord[] = [
  {
    id: "C-001",
    title: "别再收藏 AI 工具了，先搭好你的创作工作流",
    status: "待审核",
    type: "采集仿写",
    source: "S-001 + B-001",
    author: "示例用户",
    updatedAt: "今天 11:22",
    summary: "如果你收藏了几十个 AI 工具却还是写不出内容，问题可能不是工具不够，而是流程没有连起来……",
    tags: ["AI 工作流", "内容创作"],
    version: "v2",
    sourceId: "creation_demo_001",
  },
  {
    id: "C-002",
    title: "普通人做 AI 内容，先把这四步跑顺",
    status: "已采用",
    type: "原创",
    source: "B-001 + 品牌内容库",
    author: "林悦",
    updatedAt: "今天 10:40",
    summary: "从选题、拆解、创作到复盘，四步建立每周可重复的内容系统。",
    tags: ["AI 内容", "工作流"],
    version: "v3",
    sourceId: "creation_demo_002",
  },
  {
    id: "C-003",
    title: "AI 时代，最值得训练的不是提示词",
    status: "草稿",
    type: "仿写",
    source: "S-003 + B-002",
    author: "示例用户",
    updatedAt: "昨天 20:12",
    summary: "真正拉开差距的是判断任务、验证结果和持续迭代的能力。",
    tags: ["AI 能力", "成长"],
    version: "v1",
    sourceId: "creation_demo_003",
    risk: "来源事实待核实",
  },
];

export const initialTasks: Task[] = [
  {
    id: "T-1042",
    kind: "采集",
    title: "采集关键词：AI 工作流",
    status: "running",
    stage: "字段处理",
    progress: 68,
    detail: "已入库 34 / 50 条，可关闭页面继续执行",
    resultPage: "collections",
    createdAt: "11:18",
  },
  {
    id: "FS-1039",
    kind: "飞书",
    title: "同步拆解库到飞书",
    status: "partially_succeeded",
    stage: "字段写入",
    progress: 94,
    detail: "成功 324 条，2 条字段不兼容",
    resultPage: "breakdowns",
    retryable: true,
    createdAt: "11:06",
  },
];
